language: cpp
compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - gcc-7
      - g++-7

install:
  - export CC=gcc-7
  - export CXX=g++-7
  - echo ${CXX}
  - ${CXX} --version

script:
  - bash ./test/test0.sh
  - bash ./test/test1.sh

notifications:
    email: false